root = "."
tmp = "tmp"

[build]

cmd = "go build -o ./tmp/server ./server"

post_cmd = [
    "lsof -i :8090 -sTCP:LISTEN | sed 1d | awk '{print $2}' | xargs kill -9"
]

bin = "tmp/server"
full_bin = "tmp/server"

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
kill_delay = 5000 # nanosecond
