# fly.toml app configuration file generated for gonana-api on 2024-10-25T10:47:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gonana-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
