# fly.toml app configuration file generated for goanna-api on 2024-11-11T03:53:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goanna-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
